config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}


  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
  get '/become_host' => 'pages#become_host'


  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end


  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"

  #For Stripe Connect Use:
  get '/payout_method' => "users#payout"

  post '/add_card' => "users#add_card"

  get '/notification_settings' => 'settings#edit'
  post '/notification_settings' => 'settings#update'

  get '/notifications' => 'notifications#index'
  get '/wine_demand' => 'pages#wine_demand'
  get '/partnership' => 'pages#partnership'
  get 'subscribe_newsletter' => 'pages#subscribe_newsletter'
  get 'concept' => 'pages#concept'

  mount ActionCable.server => '/cable'

end

app/views/shared/_connected_menu.html.erb
<% if (user_signed_in?) && !current_page?(root_path) && !current_page?(search_path) && !current_page?(become_host_path) %>
<nav class="navbar navbar-default" style="background-color: #565A5C">
 <ul class="nav navbar-nav">
  <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "Dashboard", dashboard_path %></li>
  <% if current_user.state == 'host' %>
  <li <% if current_page?(new_room_path) %> class="active" <% end %> ><%= link_to "Add New Bootle", new_room_path %></li>
  <li <% if current_page?(rooms_path) %> class="active" <% end %> ><%= link_to "My wine cellar", rooms_path %></li>
  <li <% if current_page?(your_reservations_path) %> class="active" <% end %> ><%= link_to "Your Bookings", your_reservations_path %></li>
  <li <% if current_page?(revenues_path) %> class="active" <% end %> ><%= link_to "Revenues", revenues_path %></li>
  <% end %>
  <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "Messages", conversations_path %></li>
  <li <% if current_page?(wine_demand_path) %> class="active" <% end %> ><%= link_to "Wine demand", wine_demand_path %></li>
<!-- For Stripe Connect Use:
   link_to payout_method_path.......
 -->
</ul>
</nav>
<% end %>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to "Concept", concept_path %>
    <%= link_to "Partnership", partnership_path %>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "wine_house.png", height: 40 %>
      <%= link_to "Wines House", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if (!user_signed_in?) %>
      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>

      <% else %>

      <% if current_user.customer? %>
      <li><button class="btn btn-form btn-small">
        <%= link_to "Your Wines Purchased", your_trips_path, style: "color: white; text-decoration: none;" %></button></li>
        <% else %>
 <li><button class="btn btn-form btn-small">
        <%= link_to "Add a bootle", your_trips_path, style: "color: white; text-decoration: none;" %></button></li>

<% end %>
<!--
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>

        -->
        <li><%= link_to notifications_path do %>
          <i class="fa fa-bell fa-2x icon-babu"></i>
          <span class="badge" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
          <% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
          role="button" aria-haspopup="true" aria-expanded="false">
          <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
          <%= current_user.fullname %> <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Messages", conversations_path %></li>
          <li><%= link_to "Payment Method", payment_method_path %></li>

          <li role="separator" class="divider"></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Notifications", notification_settings_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
      <% end %>
    </ul>
  </div><!--/.nav-collapse -->
</div>
</nav>

app/views/shared/_stepper.html.erb
<!-- Stepper -->
<div class="steps-form-2">
    <div class="steps-row-2 setup-panel-2 d-flex justify-content-between">
        <div class="steps-step-2">
            <a href="#step-2" type="button" class="btn btn-blue-grey btn-circle-2 waves-effect" data-toggle="tooltip" data-placement="top" title="Sign-up as wine seller"><i class="fa fa-pencil" aria-hidden="true"></i></a>
        </div>
        <div class="steps-step-2">
            <a href="#step-3" type="button" class="btn btn-blue-grey btn-circle-2 waves-effect" data-toggle="tooltip" data-placement="top" title="Update payment infos"><i class="fa fa-credit-card" aria-hidden="true"></i></a>
        </div>
        <div class="steps-step-2">
            <a href="#step-4" type="button" class="btn btn-blue-grey btn-circle-2 waves-effect mr-0" data-toggle="tooltip" data-placement="top" title="Publish your bottles"><i class="fas fa-wine-glass" aria-hidden="true"></i></a>
        </div>
    </div>
</div>