config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}


  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
  get '/become_host' => 'pages#become_host'


  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end


  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"

  #For Stripe Connect Use:
  get '/payout_method' => "users#payout"

  post '/add_card' => "users#add_card"

  get '/notification_settings' => 'settings#edit'
  post '/notification_settings' => 'settings#update'

  get '/notifications' => 'notifications#index'
  get '/wine_demand' => 'pages#wine_demand'
  get '/partnership' => 'pages#partnership'
  get 'subscribe_newsletter' => 'pages#subscribe_newsletter'
  get 'concept' => 'pages#concept'

  mount ActionCable.server => '/cable'

end

app/models/room.rb
class Room < ApplicationRecord

  enum instant: {Request: 0, Instant: 1}

  belongs_to :user
  has_many :photos
  has_many :reservations

  has_many :guest_reviews
  has_many :calendars

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]
  before_action :is_host, only: [:new, :create, :edit, :update, :listing, :pricing, :description, :photo_upload, :amenities, :location]
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
#for Stripe Connect Use:
#    if !current_user.is_active_host
#      return redirect_to payout_method_path, alert: "Please Connect to Stripe Express first."
#    end

    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos = @room.photos
    @guest_reviews = @room.guest_reviews

#API from:
#require 'json'
#require 'open-uri'

#listing_name = @room.listing_name
#api_key = ''
#api_url ='http://services.wine.com/api/beta2/service.svc/json/catalog?search=#{listing_name}&size=5&offset=10&apikey=#{api_key}'
#quote = JSON.parse(open(api_url).read)

#@description = quote['joke']
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update

    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room

    if @room.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @room.reservations.where("(start_date >= ? OR end_date >= ?) AND status = ?", today, today, 1)
    unavailable_dates = @room.calendars.where("status = ? AND day > ?", 1, today)

    special_dates = @room.calendars.where("status = ? AND day > ? AND price <> ?",0, today, @room.price)

    render json: {
        reservations: reservations,
        unavailable_dates: unavailable_dates,
        special_dates: special_dates
    }
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("(? < start_date AND end_date < ?) AND status = ?", start_date, end_date, 1)
      check_2 = room.calendars.where("day BETWEEN ? AND ? AND status = ?", start_date, end_date, 1).limit(1)

      check.size > 0 || check_2.size > 0 ? true : false
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active, :instant)
    end

def is_host
    redirect_to dashboard_path, alert: "You don't have permission" unless current_user.state == 'host'
end


end

app/views/rooms/_room_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
<!--
          <%= image_tag room.cover_photo(:medium) %>
-->
        </div>
        <div class="panel-body">
          <%= link_to room.listing_name, room %><br/>
          $<%= room.price %> - <%= room.home_type %> - <%= pluralize(room.bed_room, "bed") %>
          <div id="star_<%= room.id %>"></div> <%= pluralize(room.average_rating, "review") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= room.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= room.average_rating %>
      });
    </script>
<% end %>

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    <% if !@room.price.blank? %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    <% if !@room.photos.blank? %>
    <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
<%= f.hidden_field :active, value: true %>
<%= f.submit "Publish", id: "publish_button", class: "btn btn-success btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview text-center">
        <!--
          <%= image_tag room.cover_photo(:medium) %>
          -->
          <%= link_to room.listing_name, room %>
        </div>
        <div class="panel-body">
          $<%= room.price %> <%= room.home_type %> <br><%= room.room_type %> <%= room.accommodate %>
          <div id="star_<%= room.id %>"></div>
            <%= image_tag avatar_url(room.user), class: "img-circle avatar-small" %> <%= pluralize(room.average_rating, "review") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= room.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= room.average_rating %>
      });
    </script>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Your conditions concerning the sale of your bootle
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_tv %> To Take Away (no delivery)
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_kitchen %> Delivered in less than 5 min
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_internet %> Delivered in less than 15 min
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_heating %> Invoice of buying
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_air %> Wine Conserved in good place
                </div>
              </div>
              <br/><br/>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-form" %>
              </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Description
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Select Type</label>
              <%= f.select :Typology, [["Chateau", "Chateau"], ["Domaine", "Domaine"], ["Clos", "Clos"]], prompt: "Select...", class: "form-control" %>
              </div>
            </div>


            <div class="row">
              <div class="form-group">
                <label>Bottle Name</label>
                <%= f.text_field :listing_name, placeholder: "Chateau Yquem...", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>Description/Rating</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Rating of your wine... (from an API)", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<%= render partial: 'shared/connected_menu' %>
<div class='container'>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Update Properties
        </div>
        <div class="panel-body">
          <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag room.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%= room.listing_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", listing_room_path(room), class: "btn btn-form" %>
            </div>
          </div>
          <hr/>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">

              <div class="col-md-4 select">
            <div class="form-group">
              <label>Type of Wine</label>
              <%= f.select :home_type, [["Champagne", "Champagne"], ["Sparkling", "Sparkling"], ["Red Wine", "Red Wine"], ["Rosé", "Rosé"], ["White Wine", "White Wine"], ["Other", "Other"]],
              id: "home_type", prompt: "Select...", class: "form-control" %>
            </div>
              </div>

              <div class="col-md-4 select">
            <div class="form-group">
              <label>Wine Appelation</label>
              <%= f.select :room_type, [["Pomerol", "Pomerol"], ["St Emilion", "St Emilion"], ["Medoc", "Medoc"], ["Other", "Other"]],
              id: "room_type", prompt: "Select...", class: "form-control" %>
            </div>
              </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Booking Type</label>
              <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, prompt: "Select...", class: "form-control" %>
            </div>
          </div>

              <div class="col-md-4 select">
            <div class="form-group">
              <label>Year</label>
              <%= f.select :accommodate, [["1980", 1980], ["1981", 1981], ["1982", 1982], ["1983", 1983]],
              id: "accommodate", prompt: "Select...", class: "form-control" %>
            </div>
              </div>

              <div class="col-md-4 select">
            <div class="form-group">
              <label>Conservation</label>
              <%= f.select :bed_room, [["Outside Temperature", "Outside Temperature"], ["Cold", "Cold"], ["Very Cold", "Very Cold"]],
              id: "bed_room", prompt: "Select...", class: "form-control" %>
            </div>
              </div>

              <div class="col-md-4 select">
            <div class="form-group">
              <label>Size of the bottle</label>
              <%= f.select :bath_room,[["0,375cl", "0,375cl"], ["0,50cl", "0,50cl"], ["0,75cl", "0,75cl"], ["1,5cl", "1,5cl"], ["3l", "3l"], ["5l", "5l"]],
              id: "bath_rooms", prompt: "Select...", class: "form-control" %>
            </div>
              </div>

            </div>

            <div><%= f.submit "Save", class: "btn btn-normal" %></div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class='container'>
  <div class="row">
    <div class="col-md-3">
      <%= render 'room_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          Location of the bottle
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Address of the bottle</label>
                <%= f.text_field :address, placeholder: "Where is the bootle?", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>

  </div>
</div>

<script>
  $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

app/views/rooms/new.html.erb
<%= render partial: 'shared/connected_menu' %>

<div class='container'>
  <div class="panel panel-default">
    <div class="panel-heading">
      Add your bootle online
    </div>
    <div class="panel-body">
      <div class="container">

        <%= form_for @room do |f| %>
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Type of Wine</label>
              <%= f.select :home_type, [["Champagne", "Champagne"], ["Sparkling Wine", "Sparkling Wine"], ["Red Wine", "Red Wine"], ["Rosé", "Rosé"], ["White Wine", "White Wine"], ["Other", "Other"]],
              id: "home_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Wine Appelation</label>
              <%= f.select :room_type, [["Pomerol", "Pomerol"], ["St Emilion", "St Emilion"], ["Medoc", "Medoc"], ["Other", "Other"]],
              id: "room_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Booking Type</label>
              <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Year</label>
              <%= f.select :accommodate, [["1980", 1980], ["1981", 1981], ["1982", 1982], ["1983", 1983]],
              id: "accommodate", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Conservation</label>
              <%= f.select :bed_room, [["Outside Temperature", "Outside Temperature"], ["Cold", "Cold"], ["Very Cold", "Very Cold"]],
              id: "bed_room", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Size of the bottle</label>
              <%= f.select :bath_room,[["0,375cl", "0,375cl"], ["0,50cl", "0,50cl"], ["0,75cl", "0,75cl"], ["1,5cl", "1,5cl"], ["3l", "3l"], ["5l", "5l"]],
              id: "bath_rooms", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

        </div>

        <div class='text-center'><%= f.submit "Add my Bottle", class: "btn btn-normal" %></div>

        <% end %>
        <div class="row text-center">
          <strong>Be carefull:<br>
            Instant booking: allows customer to book directly <br>
            Request : needs host approval before booking is approved<br>
            Customer Credit Card Info is mandatory for the 2 options</strong>
          </div>

        </div>
      </div>
    </div>
  </div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->
              <p>Please upload picture with the following size: (max: 200Ko)<br>
              (1020px/680px)</p>
              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
              <div class="row">
                <div class="form-group">
                  <span class="btn btn-default btn-file text-babu">
                    <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                    <%= file_field_tag "images[]", type: :file, multiple: true %>
                  </span>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "Add Photos", class: "btn btn-form" %>
              </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Pricing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Price</label>
                <%= f.text_field :price, placeholder: "eg: $100", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
     <div class="panel panel-default text-center">
       <div class="panel-heading">
        <%= @room.listing_name %><br>
      </div>
    </div>
  </div>
  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <div class="row text-center">
      <div class="col-xs-12 col-md-4"><span class="label label-danger"><%= @room.home_type %></span></div>
      <div class="col-xs-12 col-md-4"><span class="label label-danger"><%= @room.room_type %></span></div>
      <div class="col-xs-12 col-md-4"><span class="label label-danger"><%= @room.accommodate %></span></div>
    </div>
    <hr>
    <!-- Listing Name -->
    <div class="row">
     <div class="col-md-4 text-center">
       <%= image_tag @room.cover_photo(nil), width: 160 %><hr>
     </div>
     <div class="col-md-8">
      <%= @room.summary %>

<!-- from API
       <%= @description %>
-->
    </div>
  </div>
  <hr/>
  <!-- About -->
  <div class="row">
    <div class="col-md-12 text-center">
     Sales Conditions:<br><br>
   </div>
   <div class="col-md-6 text-left">
     <ul class="amenities">
      <li><%= image_tag 'checkbox-icon', width: 28 %> To Take Away</li>
      <li><%= image_tag 'red-checkbox', width: 28 %> Delivery around me</li>
    </ul>
  </div>
  <div class="col-md-6 text-left">

    <ul class="amenities">
      <li><%= image_tag 'checkbox-icon', width: 28 %> Invoice of buying</li>
      <li><%= image_tag 'checkbox-icon', width: 28 %> Wine correctly conserved</li>
    </ul>
  </div>
</div>
<!-- NEAR BY ROOMS -->
<div class="row">
  <div class="col-md-4">
  </div>
</div>
</div>
<!-- RIGHT PANEL -->
<!-- Reservation Form -->
<div class="col-md-4">

  <% if (!user_signed_in?) %>
  <div class="panel panel-default">
    <div class="panel-heading text-center">
      Price: <%= @room.price %> eur
    </div>
    <div class="panel-body text-center">
      <%= link_to 'Sign in to book', new_user_session_path, class:"btn btn-form btn-small" %>
      <br>
    </div>
  </div>
  <% else %>
  <%= render 'reservations/form' %>
  <% end %>

  <!-- Reviews-->
  <div class="row">
    <div class="col-md-12">
     <div class="panel panel-default text-center">
       <div class="panel-heading">
         sold by:  <%= @room.user.fullname %>
         <%= image_tag avatar_url(@room.user), class: "img-circle avatar-small" %>
         <br><%= pluralize(@guest_reviews.count, "Review") %>
         <span id="average_rating"></span>
       </div>
       <div class="container">
        <div><%= render "reviews/guest_list" %></div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div id="map" style="width: 100%; height: 200px"></div>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          center: location,
          zoom: 16
        });

        var marker = new google.maps.Marker({
          position: location,
          map: map
        });

        var infoWindow = new google.maps.InfoWindow({
          content: '<div id="content"><%= @room.listing_name %></div>'
        });

        infoWindow.open(map, marker);
      }

      google.maps.event.addDomListener(window, 'load', initialize);
    </script>




  </div>
</div>


</div>
</div>
</div>


<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @room.average_rating %>
  });
</script>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>